### =======================
### PRODUCTOS
### =======================

## Obtener todos los productos
GET http://localhost:3005/productos
Content-Type: application/json


## Obtener producto por ID
GET http://localhost:3005/productos/1
Content-Type: application/json


## Crear un nuevo producto
POST http://localhost:3005/productos
Content-Type: application/json

{
  "nombre": "Cucha Grande",
  "descripcion": "Cucha para perros grandes, plástica, resistente a la intemperie",
  "precio_lista": 18000,
  "precio_efectivo": 16500,
  "stock": 5,
  "imagen_url": "https://via.placeholder.com/150",
  "categoria_id": 1
}


## Reemplazar producto por ID
PUT http://localhost:3005/productos/1
Content-Type: application/json

{
  "nombre": "Cucha XL Nueva",
  "descripcion": "Modelo reforzado para razas extra grandes",
  "precio_lista": 19500,
  "precio_efectivo": 17500,
  "stock": 3,
  "imagen_url": "https://via.placeholder.com/150",
  "categoria_id": 1
}


## Actualizar parcialmente el producto
PATCH http://localhost:3005/productos/1
Content-Type: application/json

{
  "stock": 12,
  "precio_lista": 18500
}


## Eliminar producto por ID
DELETE http://localhost:3005/productos/1
Content-Type: application/json


### =======================
### USUARIOS + JWT
### =======================

## 1) LOGIN -> Obtener token
POST http://localhost:3005/usuarios/register
Content-Type: application/json

{
  "name": "Yazmin",
  "mail": "yaaz97@gmail.com",
  "password": "gato",
  "type": "admin"
}